import type { Coordinate } from '../types'

// Replace the MVP envelope with the official Distrito Capital polygon generated by the data pipeline.
export const BOGOTA_BOUNDS: [[number, number], [number, number]] = [[-74.25, 4.45], [-73.95, 4.90]]
// Ventana amplia para permitir zoomout. La máscara administrativa continúa
// ocultando todo lo que queda fuera de Bogotá.
export const MAP_VIEW_BOUNDS: [[number, number], [number, number]] = [[-75.20, 3.80], [-73.00, 5.60]]
export const BOGOTA_CENTER: Coordinate = [-74.0721, 4.711]

export function isInsideBogota([lon, lat]: Coordinate): boolean {
  return lon >= BOGOTA_BOUNDS[0][0] && lon <= BOGOTA_BOUNDS[1][0] && lat >= BOGOTA_BOUNDS[0][1] && lat <= BOGOTA_BOUNDS[1][1]
}
